// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmDMq8TOvGeVJGGERMoPoL1sqPolcGGg0',
    appId: '1:336754784564:web:17e8201b9cc2fee2ac4d61',
    messagingSenderId: '336754784564',
    projectId: 'hireready-pk',
    authDomain: 'hireready-pk.firebaseapp.com',
    storageBucket: 'hireready-pk.firebasestorage.app',
    measurementId: 'G-W0SHW4461P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2vkG7-xTyxwsRsOkwLox0Rv7WA0vh4t8',
    appId: '1:336754784564:android:c36c9e969617e86aac4d61',
    messagingSenderId: '336754784564',
    projectId: 'hireready-pk',
    storageBucket: 'hireready-pk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmDMq8TOvGeVJGGERMoPoL1sqPolcGGg0',
    appId: '1:336754784564:web:f5c599e73c54316aac4d61',
    messagingSenderId: '336754784564',
    projectId: 'hireready-pk',
    authDomain: 'hireready-pk.firebaseapp.com',
    storageBucket: 'hireready-pk.firebasestorage.app',
    measurementId: 'G-F4X5RJBN03',
  );
}
